# Generated by Django 5.2.8 on 2026-02-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='priority_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
