# Generated by Django 5.2.8 on 2026-02-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
