# Generated by Django 5.2.15 on 2026-06-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('tutor', 'Tutor'), ('staff', 'Working Staff')], default='tutor', max_length=10)),
                ('bio', models.TextField(blank=True)),
                ('expertise', models.CharField(blank=True, help_text='Comma-separated list of expertise tags, e.g., Arduino, ROS, CAD', max_length=255)),
                ('linkedin', models.URLField(blank=True, max_length=255)),
                ('github', models.URLField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
