# Generated by Django 5.2.15 on 2026-06-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_staffmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='github',
        ),
    ]
