# Generated by Django 5.2.8 on 2026-02-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_innovative_project',
            field=models.BooleanField(default=False),
        ),
    ]
